version: "3.0"
services:
  mongodb:
    image: mongo:4.4.2
    network_mode: host
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456